version: '3.8'

services:
  # MongoDB
  mongodb:
    image: mongo:7.0
    container_name: sam-mongodb
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin123
      MONGO_INITDB_DATABASE: sam_opportunities
    volumes:
      - mongodb_data:/data/db
      - ./docker/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    networks:
      - sam-network

  # Neo4j for GraphRAG
  neo4j:
    image: neo4j:5.14
    container_name: sam-neo4j
    restart: always
    ports:
      - "7474:7474"  # HTTP
      - "7687:7687"  # Bolt
    environment:
      NEO4J_AUTH: neo4j/password123
      NEO4J_PLUGINS: '["apoc", "graph-data-science"]'
      NEO4J_dbms_memory_pagecache_size: 1G
      NEO4J_dbms_memory_heap_max__size: 1G
    volumes:
      - neo4j_data:/data
      - neo4j_logs:/logs
    networks:
      - sam-network

  # Ollama for LLM
  ollama:
    image: ollama/ollama:latest
    container_name: sam-ollama
    restart: always
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    networks:
      - sam-network
    deploy:
      resources:
        limits:
          memory: 4G
    command: serve

  # Main Application
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: sam-app
    restart: always
    ports:
      - "80:80"       # Nginx frontend
      - "5001:5001"   # Flask API
    environment:
      SAM_API_KEY: ${SAM_API_KEY}
      MONGODB_URI: mongodb://admin:admin123@mongodb:27017/sam_opportunities?authSource=admin
      NEO4J_URI: bolt://neo4j:7687
      NEO4J_USER: neo4j
      NEO4J_PASSWORD: password123
      OLLAMA_URL: http://ollama:11434
      SYNC_INTERVAL_MINUTES: 15
    depends_on:
      - mongodb
      - neo4j
      - ollama
    volumes:
      - ./config.yaml:/app/config.yaml:ro
      - app_logs:/app/logs
    networks:
      - sam-network

  # Scheduler Service (separate container for better scalability)
  scheduler:
    build:
      context: .
      dockerfile: Dockerfile.scheduler
    container_name: sam-scheduler
    restart: always
    environment:
      SAM_API_KEY: ${SAM_API_KEY}
      MONGODB_URI: mongodb://admin:admin123@mongodb:27017/sam_opportunities?authSource=admin
      SYNC_INTERVAL_MINUTES: 15
    depends_on:
      - mongodb
    volumes:
      - ./config.yaml:/app/config.yaml:ro
      - scheduler_logs:/app/logs
    networks:
      - sam-network

volumes:
  mongodb_data:
  neo4j_data:
  neo4j_logs:
  ollama_data:
  app_logs:
  scheduler_logs:

networks:
  sam-network:
    driver: bridge